"""empty message

Revision ID: 37383445e1c3
Revises: 18d30bce5869
Create Date: 2024-05-15 21:50:59.393716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37383445e1c3'
down_revision = '18d30bce5869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
